variables:
  GIT_SSL_NO_VERIFY: "true"

stages:
  - test

test_vsphere_connectivity:
  stage: test
  script:
    - sudo yum update -y  # Pro CentOS/RHEL
    - sudo yum install -y telnet
    - telnet 10.207.0.18 22
